language: node_js
node_js:
  - "node"
  - "lts/*"
cache:
  directories:
    - "node_modules"
script:
  - npm run cover
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
